#!/bin/bash
# Check if the code builds
go build -o gn
if [ $? -ne 0 ]; then
	echo "Failed to build!"
	exit 1
fi
rm gn

# Run formater
out=$(gofumpt -w .)
if [ $? -ne 0 ]; then
	echo "Formater failed!"
	echo "$out"
	exit 1
fi

# Sort imports
out=$(goimports -w *.go)
if [ $? -ne 0 ]; then
	echo "Sorting imports failed!"
	echo "$out"
	exit 1
fi

# Check struct alignment
out=$(betteralign ./...)
if [ $? -ne 0 ]; then
	echo "There are misaligned structs!"
	echo "$out"
	exit 1
fi

# Run golangcli-lint
golangci-lint run
if [ $? -ne 0 ]; then
	echo
	echo "golangcli has found some issues"
	exit 1
fi

exit 0
